export const DEFAULT_ACTION = 'app/OverTimeManager/DEFAULT_ACTION';

export const MERGE_DATA = 'app/TakeLeaveManager/MERGE_DATA';

export const ADD_TAKE_LEAVE_MANAGER = 'app/TakeLeaveManager/ADD_TAKE_LEAVE_MANAGER';
export const ADD_TAKE_LEAVE_MANAGER_SUCCESS = 'app/TakeLeaveManager/ADD_TAKE_LEAVE_MANAGER_SUCCESS';
export const ADD_TAKE_LEAVE_MANAGER_FAILURE = 'app/TakeLeaveManager/ADD_TAKE_LEAVE_MANAGER_FAILURE';

export const UPDATE_TAKE_LEAVE_MANAGER = 'app/TakeLeaveManager/UPDATE_TAKE_LEAVE_MANAGER';
export const UPDATE_TAKE_LEAVE_MANAGER_SUCCESS = 'app/TakeLeaveManager/UPDATE_TAKE_LEAVE_MANAGER_SUCCESS';
export const UPDATE_TAKE_LEAVE_MANAGER_FAILURE = 'app/TakeLeaveManager/UPDATE_TAKE_LEAVE_MANAGER_FAILURE';

export const DELETE_TAKE_LEAVE_MANAGER = 'app/TakeLeaveManager/DELETE_TAKE_LEAVE_MANAGER';
export const DELETE_TAKE_LEAVE_MANAGER_SUCCESS = 'app/TakeLeaveManager/DELETE_TAKE_LEAVE_MANAGER_SUCCESS';
export const DELETE_TAKE_LEAVE_MANAGER_FAILURE = 'app/TakeLeaveManager/DELETE_TAKE_LEAVE_MANAGER_FAILURE';

export const GET_ALL_VACATION_MODE = 'app/TakeLeaveManager/GET_ALL_VACATION_MODE';
export const GET_ALL_VACATION_MODE_SUCCESS = 'app/TakeLeaveManager/GET_ALL_VACATION_MODE_SUCCESS';
export const GET_ALL_VACATION_MODE_FAILURE = 'app/TakeLeaveManager/GET_ALL_VACATION_MODE_FAILURE';