/*
 *
 * TimekeepingPage constants
 *
 */

export const DEFAULT_ACTION = 'app/TimekeepingPage/DEFAULT_ACTION';

export const MERGE_DATA = 'app/TimekeepingPage/MERGE_DATA';

export const CREATE_WAGES = 'app/TimekeepingPage/CREATE_WAGES';
export const CREATE_WAGES_SUCCESS = 'app/TimekeepingPage/CREATE_WAGES_SUCCESS';
export const CREATE_WAGES_FAILURE = 'app/TimekeepingPage/CREATE_WAGES_FAILURE';

export const UPDATE_WAGES = 'app/TimekeepingPage/UPDATE_WAGES';
export const UPDATE_WAGES_SUCCESS = 'app/TimekeepingPage/UPDATE_WAGES_SUCCESS';
export const UPDATE_WAGES_FAILURE = 'app/TimekeepingPage/UPDATE_WAGES_FAILURE';

export const DELETE_WAGES = 'app/TimekeepingPage/DELETE_WAGES';
export const DELETE_WAGES_SUCCESS = 'app/TimekeepingPage/DELETE_WAGES_SUCCESS';
export const DELETE_WAGES_FAILURE = 'app/TimekeepingPage/DELETE_WAGES_FAILURE';

export const GET_ALL_TIMEKEEPING_EQUIPMENT = 'app/ImportPage/GET_ALL_TIMEKEEPING_EQUIPMENT';
export const GET_ALL_TIMEKEEPING_EQUIPMENT_SUCCESS = 'app/ImportPage/GET_ALL_TIMEKEEPING_EQUIPMENT_SUCCESS';
export const GET_ALL_TIMEKEEPING_EQUIPMENT_FAILURE = 'app/ImportPage/GET_ALL_TIMEKEEPING_EQUIPMENT_FAILURE';

export const GET_TIMEKEEPING_TO_EQUIPMENT = 'app/ImportPage/GET_TIMEKEEPING_TO_EQUIPMENT';
export const GET_TIMEKEEPING_TO_EQUIPMENT_SUCCESS = 'app/ImportPage/GET_TIMEKEEPING_TO_EQUIPMENT_SUCCESS';
export const GET_TIMEKEEPING_TO_EQUIPMENT_FAILURE = 'app/ImportPage/GET_TIMEKEEPING_TO_EQUIPMENT_FAILURE';

export const IMPORT_TIMEKEEPING = 'app/ImportPage/IMPORT_TIMEKEEPING';
export const IMPORT_TIMEKEEPING_SUCCESS = 'app/ImportPage/IMPORT_TIMEKEEPING_SUCCESS';
export const IMPORT_TIMEKEEPING_FAILURE = 'app/ImportPage/IMPORT_TIMEKEEPING_FAILURE';

export const ADD_TAKE_LEAVE_MANAGER = 'app/TimekeepingPage/ADD_TAKE_LEAVE_MANAGER';
export const ADD_TAKE_LEAVE_MANAGER_SUCCESS = 'app/TimekeepingPage/ADD_TAKE_LEAVE_MANAGER_SUCCESS';
export const ADD_TAKE_LEAVE_MANAGER_FAILURE = 'app/TimekeepingPage/ADD_TAKE_LEAVE_MANAGER_FAILURE';

export const UPDATE_TAKE_LEAVE_MANAGER = 'app/TimekeepingPage/UPDATE_TAKE_LEAVE_MANAGER';
export const UPDATE_TAKE_LEAVE_MANAGER_SUCCESS = 'app/TimekeepingPage/UPDATE_TAKE_LEAVE_MANAGER_SUCCESS';
export const UPDATE_TAKE_LEAVE_MANAGER_FAILURE = 'app/TimekeepingPage/UPDATE_TAKE_LEAVE_MANAGER_FAILURE';

export const DELETE_TAKE_LEAVE_MANAGER = 'app/TimekeepingPage/DELETE_TAKE_LEAVE_MANAGER';
export const DELETE_TAKE_LEAVE_MANAGER_SUCCESS = 'app/TimekeepingPage/DELETE_TAKE_LEAVE_MANAGER_SUCCESS';
export const DELETE_TAKE_LEAVE_MANAGER_FAILURE = 'app/TimekeepingPage/DELETE_TAKE_LEAVE_MANAGER_FAILURE';