export const CREATE_ACCOUNT_REQUESTED = 'app/LtAccount/CREATE_ACCOUNT_REQUESTED';
export const CREATE_ACCOUNT_REQUESTED_SUCCEEDED = 'app/LtAccount/CREATE_ACCOUNT_REQUESTED_SUCCEEDED';
export const CREATE_ACCOUNT_REQUESTED_FAILED = 'app/LtAccount/CREATE_ACCOUNT_REQUESTED_FAILED';

export const UPDATE_ACCOUNT_REQUESTED = 'app/LtAccount/UPDATE_ACCOUNT_REQUESTED';
export const UPDATE_ACCOUNT_REQUESTED_SUCCEEDED = 'app/LtAccount/UPDATE_ACCOUNT_REQUESTED_SUCCEEDED';
export const UPDATE_ACCOUNT_REQUESTED_FAILED = 'app/LtAccount/UPDATE_ACCOUNT_REQUESTED_FAILED';

export const UPDATE_PASSWORD_REQUESTED = 'app/LtAccount/UPDATE_PASSWORD_REQUESTED';
export const UPDATE_PASSWORD_REQUESTED_SUCCEEDED = 'app/LtAccount/UPDATE_PASSWORD_REQUESTED_SUCCEEDED';
export const UPDATE_PASSWORD_REQUESTED_FAILED = 'app/LtAccount/UPDATE_PASSWORD_REQUESTED_FAILED';

export const MERGE_DATA = 'app/LtAccount/MERGE_DATA';
