/*
 *
 * WagesSalary constants
 *
 */

export const MERGE_DATA = 'app/WagesSalary/MERGE_DATA';

export const CREATE_WAGE_SALARY = 'app/WagesSalary/CREATE_WAGE_SALARY';
export const CREATE_WAGE_SALARY_SUCCESS = 'app/WagesSalary/CREATE_WAGE_SALARY_SUCCESS';
export const CREATE_WAGE_SALARY_FAILURE = 'app/WagesSalary/CREATE_WAGE_SALARY_FAILURE';

export const UPDATE_WAGE_SALARY = 'app/WagesSalary/UPDATE_WAGE_SALARY';
export const UPDATE_WAGE_SALARY_SUCCESS = 'app/WagesSalary/UPDATE_WAGE_SALARY_SUCCESS';
export const UPDATE_WAGE_SALARY_FAILURE = 'app/WagesSalary/UPDATE_WAGE_SALARY_FAILURE';

export const DELETE_WAGE_SALARY = 'app/WagesSalary/DELETE_WAGE_SALARY';
export const DELETE_WAGE_SALARY_SUCCESS = 'app/WagesSalary/DELETE_WAGE_SALARY_SUCCESS';
export const DELETE_WAGE_SALARY_FAILURE = 'app/WagesSalary/DELETE_WAGE_SALARY_FAILURE';

export const GET_ALL_SALARY_FORMULA = 'app/WagesSalary/GET_ALL_SALARY_FORMULA';
export const GET_ALL_SALARY_FORMULA_SUCCESS = 'app/WagesSalary/GET_ALL_SALARY_FORMULA_SUCCESS';
export const GET_ALL_SALARY_FORMULA_FAILURE = 'app/WagesSalary/GET_ALL_SALARY_FORMULA_FAILURE';

export const GET_SALARY_FORMULA_ATTRIBUTES = 'app/WagesSalary/GET_SALARY_FORMULA_ATTRIBUTES';
export const GET_SALARY_FORMULA_ATTRIBUTES_SUCCESS = 'app/WagesSalary/GET_SALARY_FORMULA_ATTRIBUTES_SUCCESS';
export const GET_SALARY_FORMULA_ATTRIBUTES_FAILURE = 'app/WagesSalary/GET_SALARY_FORMULA_ATTRIBUTES_FAILURE';