const data = [
  {
    name: 'Công ty cà phê Trung Nguyên',
    code: 'pd1',
    otherName: 'p1',
    id: 1,
    stt: 1,
    subDepartment: [
      {
        name: 'Phòng nhân sự',
        code: 'pd1',
        otherName: 'PNS',
        stt: 1,
        subDepartment: [],
        id: 2,
      },
      {
        name: 'Phòng quản trị',
        code: 'pd1',
        otherName: 'p1',
        stt: 1,
        id: 3,
        subDepartment: [
          {
            name: 'Quản trị vốn',
            code: 'pd1',
            otherName: 'p1',
            stt: 1,
            id: 4,
            subDepartment: [],
          },
          {
            name: 'Quản trị lưu động',
            code: 'pd1',
            otherName: 'p1',
            stt: 1,
            id: 5,
            subDepartment: [],
          },
          {
            name: 'Quản trị Nguồn hàng',
            code: 'pd1',
            otherName: 'p1',
            stt: 1,
            id: 5,
            subDepartment: [],
          },
        ],
      },
      {
        name: 'Phòng sản phẩm',
        code: 'pd1',
        otherName: 'p1',
        stt: 1,
        id: 3,
        subDepartment: [
          {
            name: 'Cà phê trồn',
            code: 'pd1',
            otherName: 'p1',
            stt: 1,
            id: 4,
            subDepartment: [],
          },
          {
            name: 'Cà phê đen',
            code: 'pd1',
            otherName: 'p1',
            stt: 1,
            id: 5,
            subDepartment: [],
          },
          {
            name: 'Cà phê nâu',
            code: 'pd1',
            otherName: 'p1',
            stt: 1,
            id: 5,
            subDepartment: [],
          },
        ],
      },
    ],
  },
  {
    name: 'Công ty cà phê hòa tan Trung Nguyên',
    code: 'pd1',
    otherName: 'p1',
    stt: 1,
    id: 6,
    subDepartment: [],
  },
  {
    name: 'Công ty cà phê hòa tan Trung Nguyên',
    code: 'pd1',
    otherName: 'p1',
    stt: 1,
    id: 6,
    subDepartment: [],
  },
  {
    name: 'Công ty cà phê hòa tan Trung Nguyên',
    code: 'pd1',
    otherName: 'p1',
    stt: 1,
    id: 6,
    subDepartment: [],
  },
  {
    name: 'Công ty cà phê hòa tan Trung Nguyên',
    code: 'pd1',
    otherName: 'p1',
    stt: 1,
    id: 6,
    subDepartment: [],
  },
  {
    name: 'Công ty chuỗi cà phê Trung Nguyên',
    code: 'pd1',
    otherName: 'p1',
    id: 1,
    stt: 1,
    subDepartment: [
      {
        name: 'Phòng nhân sự',
        code: 'pd1',
        otherName: 'PNS',
        stt: 1,
        subDepartment: [],
        id: 2,
      },
      {
        name: 'Phòng quản trị',
        code: 'pd1',
        otherName: 'p1',
        stt: 1,
        id: 3,
        subDepartment: [
          {
            name: 'Quản trị vốn',
            code: 'pd1',
            otherName: 'p1',
            stt: 1,
            id: 4,
            subDepartment: [],
          },
          {
            name: 'Quản trị lưu động',
            code: 'pd1',
            otherName: 'p1',
            stt: 1,
            id: 5,
            subDepartment: [],
          },
          {
            name: 'Quản trị Nguồn hàng',
            code: 'pd1',
            otherName: 'p1',
            stt: 1,
            id: 5,
            subDepartment: [],
          },
        ],
      },
      {
        name: 'Phòng sản phẩm',
        code: 'pd1',
        otherName: 'p1',
        stt: 1,
        id: 3,
        subDepartment: [
          {
            name: 'Cà phê trồn',
            code: 'pd1',
            otherName: 'p1',
            stt: 1,
            id: 4,
            subDepartment: [],
          },
          {
            name: 'Cà phê đen',
            code: 'pd1',
            otherName: 'p1',
            stt: 1,
            id: 5,
            subDepartment: [],
          },
          {
            name: 'Cà phê nâu',
            code: 'pd1',
            otherName: 'p1',
            stt: 1,
            id: 5,
            subDepartment: [],
          },
        ],
      },
    ],
  },
];

export default data;
