// report
// TT - "TÌM KIẾM MENU ĐANG ĐƯỢC CHỌN" = thuộc tính MENU - ĐỂ HIỂN THỊ SELECTBOX + CALL API =  2 thuộc tính : "PATH + NAME"
export const MENU_REPORTS = {
  MENU_FAVORITE: [
    { path: 'balances-funds-banks', text: 'Số dư tại quỹ và các ngân hàng', menu: 0, name: 'balanceFundBank' },
    // { path: 'average', text: 'Tỷ lệ thu chi bình quân/ tháng', menu: 1, name: 'averageRateByMonth' },
    // { path: 'comparevalue-obtanied-annually', text: 'So sánh giá trị thu hàng năm', menu: 2, name: 'compareValueAnnually' },
    // { path: 'general-sales-situation', text: 'Tổng hợp tình hình bán hàng', menu: 3, name: 'generalSaleSituation' },
    // { path: 'report-sales-by-area', text: 'Tổng hợp bán hàng theo khu vực', menu: 4, name: 'area' },
    // { path: 'comparesalesbyyear', text: 'So sánh doanh số theo năm', menu: 5, name: 'compareSalesYear' },
    // { path: 'aggregatesales-of-businesstaff?flag=true', text: 'Chi tiết bán hàng theo nhân viên kinh doanh', menu: 6, name: 'detailSaleStaff' },
    // { path: 'report-expense-in-year', text: 'Tổng hợp chi phí trong năm', menu: 7, name: 'costYear' },
    // { path: 'report-expense-by-type', text: 'Tỷ trọng chi phí theo khoản mục', menu: 8, name: 'costType' },
    // { path: 'proportion-cost-department', text: 'Tỷ trọng chi phí theo bộ phận', menu: 9, name: 'costDepartment' },
    // // ??? BỎ PHẦN : menu === 10 : Tổng chi phí ??? nếu làm phải sửa thành: menu === 13
    // // { path: 'costs', text: 'Tổng chi phí', menu: 10, name: 'costs' },
    // { path: 'aggregateinventory-by-productgroup', text: 'Tổng hợp tồn kho theo nhóm sản phẩm', menu: 10, name: 'inventoryProductGroup' },
    // { path: 'sumdebt-bussiness-staff', text: 'Tổng hợp công nợ theo nhân viên kd', menu: 11, name: 'sumDebtStaff' },
    // { path: 'balances-funds-banks', text: 'Tổng hợp công nợ theo tỉnh thành', menu: 12, name: 'debtCity' },
  ],
  MENU_SALE_MANAGER: [
    { path: 'productSales', text: 'Doanh số theo sản phẩm', sale: 17 },
    { path: 'spend', text: 'Thực hiện chỉ tiêu doanh số', sale: 0 },
    { path: 'sales', text: 'Tỷ trọng doanh số theo khu vực', sale: 1 },
    { path: 'city', text: 'Tỷ trọng doanh số theo tỉnh thành', sale: 2 },
    { path: 'employees', text: 'Tỷ trọng doanh số theo nhân viên kd', sale: 3 },
    { path: 'employeesSale', text: 'So sánh doanh số của nhân viên bán hàng trong năm', sale: 4 },
    { path: 'product', text: 'Tỷ trọng doanh số theo nhóm sản phẩm', sale: 5 },
    { path: 'type', text: 'Tỷ trọng doanh số theo loại hình', sale: 6 },
    { path: 'category', text: 'Tỷ trọng doanh số theo ngành hàng', sale: 7 },
    { path: 'customer', text: 'Top doanh số theo khách hàng', sale: 8 },
    { path: 'item', text: 'Top doanh số theo mặt hàng', sale: 9 },
    { path: 'targetYear', text: 'Tỷ lệ hoàn thành chỉ tiêu doanh số năm', sale: 10 },
    { path: 'targetMonth', text: 'Tỷ lệ hoàn thành chỉ tiêu doanh số tháng', sale: 11 },
    { path: 'total', text: 'Tổng doanh số', sale: 12 },
    { path: 'highestInMonth', text: 'Đạt doanh số cao nhất trong tháng', sale: 13 },
    { path: 'compolete', text: 'Đạt tỷ lệ hoàn thành doanh số cao nhất trong tháng', sale: 14 },
    { path: 'highestInYear', text: 'Đạt doanh số cao nhất trong năm', sale: 15 },
  ],
  MENU_EXPENSE_MANAGER: [
    // { path: 'costByDepartmentAndItem', text: 'Tổng hợp chi phí theo bộ phận và khoản mục', expense: 0 },
    // { path: 'costInMonthByDepartment', text: 'Tổng hợp chi phí trong tháng theo bộ phận', expense: 1 },

    // { path: 'totalAnnualBudget', text: 'Tổng ngân sách năm', expense: 3 },
    { path: 'reportCostRatio', text: 'Tỷ trọng chi phí', expense: 0 },
    { path: 'reportCostRatioItem', text: 'Tỷ trọng chi phí theo khoản mục', expense: 1 },
  ],
  MENU_STOCK: [
    { path: '', text: 'Tổng hợp tồn kho theo loại hình', tab: 1 },
    { path: '', text: 'Tổng hợp tồn kho theo ngành hàng', tab: 2 },
    { path: '', text: 'Giá trị tồn kho theo thời gian', tab: 3 },
    { path: '', text: 'Tổng hợp tồn kho theo nhóm sản phẩm', tab: 4 },
    { path: '', text: 'Tổng hợp giá trị tồn kho trong năm', tab: 5 },
    { path: '', text: 'Báo cáo tồn kho', tab: 6 },
  ],
  MENU_GENERAL_MANAGER: [
    { path: 'totalRevenueAndExpensesInYear', text: 'Tổng hợp doanh thu, chi phí trong năm', tab: 0 },
    { path: 'tableOfTrackingSalesOrders', text: 'Bảng theo dõi các đơn hàng bán', tab: 1 },
    { path: 'summaryOfRevenueCostOfGoodInYear', text: 'Tổng hợp doanh thu, giá vốn trong năm', tab: 2 },
    { path: 'generalRevenueAndInventoryInYear', text: 'Tổng hợp doanh thu, tồn kho trong năm', tab: 3 },
    { path: 'SumOfProfitsByItem', text: 'Tổng hợp lợi nhuận theo mặt hàng', tab: 4 },
    { path: 'GeneralBusiness', text: 'Tổng hợp kinh doanh', tab: 5 },
    { path: 'totalProfit', text: 'Tổng lợi nhuận', tab: 6 },
  ],
  MENU_RECEIVABLE_MANAGER: [
    { path: 'reportDebtEmployees', text: 'Tổng hợp công nợ theo nhân viên kinh doanh', tab: 0 },
    { path: 'reportDebtToPay', text: 'Số dư công nợ phải trả theo thời gian', tab: 1 },
    { path: 'reportDebtReceivables', text: 'Số dư công nợ phải thu theo thời gian', tab: 2 },
  ],
  MENU_PAY_MANAGER: [
    { path: 'summaryOfDebtByRegion', text: 'Tổng hợp công nợ theo khu vực', tab: 0 },
    { path: 'summaryOfDebtAccordingToSalesStaff', text: 'Tổng hợp công nợ theo nhân viên kd', tab: 1 },
    { path: 'receivableBalanceOT', text: 'Số dư công nợ phải thu theo thời gian', tab: 2 },
    { path: 'totalLiabilities', text: 'Tổng hợp công nợ phải trả', tab: 3 },
  ],
};

export const EXPORT_FILE_NAME = {
  excelTableBySign: "BÁO CÁO THỐNG KÊ THEO THÂM NIÊN ",
  excelTableOrg: "BÁO CÁO THỐNG KÊ NHÂN SỰ THEO PHÒNG BAN",
  excelTableWageOrg:"BÁO CÁO LƯƠNG",
  reportsHrmAboutExpireCotract:"BÁO CÁO THỐNG KÊ NHÂN SỰ SẮP HẾT HẠN HỢP ĐỒNG",
  hrm: 'HỒ SƠ NHÂN SỰ',
  Stock: 'KHO',
  excelTableBosReport1:"CHI TIẾT BẢNG LƯƠNG",
  Documentary: 'CÔNG VĂN',
  Delivery: 'GIAO NHẬN',
  RevenueExpenditure: 'TÀI CHÍNH NỘI BỘ',
  DocumentaryST14: 'TÀI CHÍNH NỘI BỘ',
  OrderPoundefined:"MUA Hàng",
  CustomerST18: 'KHÁCH HÀNG',
  excelTableBosReport: 'BÁO CÁO THỐNG KÊ CƠ HỘI KINH DOANH',
  reportMeetingCustomer: 'BÁO CÁO TIẾP XÚC KHÁCH HÀNG',
  reportStatsHrm: 'BÁO CÁO THỐNG KÊ NHÂN SỰ',
  reportDoingTask: 'BÁO CÁO THỜI GIAN THỰC HIỆN CÔNG VIỆC',
  reportsTaskStatus: 'BÁO CÁO TRẠNG THÁI CÔNG VIỆC',
  reportTaskWeek: 'BÁO CÁO CÔNG TÁC TUẦN',
  reportTaskSummary: 'BÁO CÁO TỔNG HỢP CÔNG VIỆC',
  reportContractValueAndPaid: 'BÁO CÁO TỔNG HỢP GIÁ TRỊ HỢP ĐỒNG VÀ THANH TOÁN',
  reportGroupProduct: 'BÁO CÁO THEO NHÓM SẢN PHẨM',
  reportCampain: 'BÁO CÁO THEO CHIẾN DỊCH',
  reportChannel: 'BÁO CÁO THEO KÊNH',

};
