export const CREATE_ACCOUNT_REQUESTED = 'app/BankAccount/CREATE_ACCOUNT_REQUESTED';
export const CREATE_ACCOUNT_REQUESTED_SUCCEEDED = 'app/BankAccount/CREATE_ACCOUNT_REQUESTED_SUCCEEDED';
export const CREATE_ACCOUNT_REQUESTED_FAILED = 'app/BankAccount/CREATE_ACCOUNT_REQUESTED_FAILED';

export const MERGE_DATA = 'app/BankAccount/MERGE_DATA';
