/*
 *
 * RecruitmentWavePage constants
 *
 */

export const DEFAULT_ACTION = 'app/RecruitmentWavePage/DEFAULT_ACTION';

export const CREATE_RECRUIMENTWAVE = 'app/RecruitmentWavePage/CREATE_RECRUIMENTWAVE';
export const CREATE_RECRUIMENTWAVE_SUCCESS = 'app/RecruitmentWavePage/CREATE_RECRUIMENTWAVE_SUCCESS';
export const CREATE_RECRUIMENTWAVE_FAILURE = 'app/RecruitmentWavePage/CREATE_RECRUIMENTWAVE_FAILURE';

export const UPDATE_RECRUIMENTWAVE = 'app/RecruitmentWavePage/UPDATE_RECRUIMENTWAVE';
export const UPDATE_RECRUIMENTWAVE_SUCCESS = 'app/RecruitmentWavePage/UPDATE_RECRUIMENTWAVE_SUCCESS';
export const UPDATE_RECRUIMENTWAVE_FAILURE = 'app/RecruitmentWavePage/UPDATE_RECRUIMENTWAVE_FAILURE';

export const DELETE_RECRUIMENTWAVE = 'app/RecruitmentWavePage/DELETE_RECRUIMENTWAVE';
export const DELETE_RECRUIMENTWAVE_SUCCESS = 'app/RecruitmentWavePage/DELETE_RECRUIMENTWAVE_SUCCESS';
export const DELETE_RECRUIMENTWAVE_FAILURE = 'app/RecruitmentWavePage/DELETE_RECRUIMENTWAVE_FAILURE';

export const CREATE_ROUNDRECRUIMENT = 'app/RecruitmentWavePage/CREATE_ROUNDRECRUIMENT';
export const CREATE_ROUNDRECRUIMENT_SUCCESS = 'app/RecruitmentWavePage/CREATE_ROUNDRECRUIMENT_SUCCESS';
export const CREATE_ROUNDRECRUIMENT_FAILURE = 'app/RecruitmentWavePage/CREATE_ROUNDRECRUIMENT_FAILURE';

export const UPDATE_ROUNDRECRUIMENT = 'app/RecruitmentWavePage/UPDATE_ROUNDRECRUIMENT';
export const UPDATE_ROUNDRECRUIMENT_SUCCESS = 'app/RecruitmentWavePage/UPDATE_ROUNDRECRUIMENT_SUCCESS';
export const UPDATE_ROUNDRECRUIMENT_FAILURE = 'app/RecruitmentWavePage/UPDATE_ROUNDRECRUIMENT_FAILURE';

export const DELETE_ROUNDRECRUIMENT = 'app/RecruitmentWavePage/DELETE_ROUNDRECRUIMENT';
export const DELETE_ROUNDRECRUIMENT_SUCCESS = 'app/RecruitmentWavePage/DELETE_ROUNDRECRUIMENT_SUCCESS';
export const DELETE_ROUNDRECRUIMENT_FAILURE = 'app/RecruitmentWavePage/DELETE_ROUNDRECRUIMENT_FAILURE';

export const CREATE_SUBJECTRECRUIMENT = 'app/RecruitmentWavePage/CREATE_SUBJECTRECRUIMENT';
export const CREATE_SUBJECTRECRUIMENT_SUCCESS = 'app/RecruitmentWavePage/CREATE_SUBJECTRECRUIMENT_SUCCESS';
export const CREATE_SUBJECTRECRUIMENT_FAILURE = 'app/RecruitmentWavePage/CREATE_SUBJECTRECRUIMENT_FAILURE';

export const UPDATE_SUBJECTRECRUIMENT = 'app/RecruitmentWavePage/UPDATE_SUBJECTRECRUIMENT';
export const UPDATE_SUBJECTRECRUIMENT_SUCCESS = 'app/RecruitmentWavePage/UPDATE_SUBJECTRECRUIMENT_SUCCESS';
export const UPDATE_SUBJECTRECRUIMENT_FAILURE = 'app/RecruitmentWavePage/UPDATE_SUBJECTRECRUIMENT_FAILURE';

export const DELETE_SUBJECTRECRUIMENT = 'app/RecruitmentWavePage/DELETE_SUBJECTRECRUIMENT';
export const DELETE_SUBJECTRECRUIMENT_SUCCESS = 'app/RecruitmentWavePage/DELETE_SUBJECTRECRUIMENT_SUCCESS';
export const DELETE_SUBJECTRECRUIMENT_FAILURE = 'app/RecruitmentWavePage/DELETE_SUBJECTRECRUIMENT_FAILURE';

export const CREATE_APPLICANTRECRUITMENT = 'app/RecruitmentWavePage/CREATE_APPLICANTRECRUITMENT';
export const CREATE_APPLICANTRECRUITMENT_SUCCESS = 'app/RecruitmentWavePage/CREATE_APPLICANTRECRUITMENT_SUCCESS';
export const CREATE_APPLICANTRECRUITMENT_FAILURE = 'app/RecruitmentWavePage/CREATE_APPLICANTRECRUITMENT_FAILURE';

export const UPDATE_APPLICANTRECRUITMENT = 'app/RecruitmentWavePage/UPDATE_APPLICANTRECRUITMENT';
export const UPDATE_APPLICANTRECRUITMENT_SUCCESS = 'app/RecruitmentWavePage/UPDATE_APPLICANTRECRUITMENT_SUCCESS';
export const UPDATE_APPLICANTRECRUITMENT_FAILURE = 'app/RecruitmentWavePage/UPDATE_APPLICANTRECRUITMENT_FAILURE';

export const DELETE_APPLICANTRECRUITMENT = 'app/RecruitmentWavePage/DELETE_APPLICANTRECRUITMENT';
export const DELETE_APPLICANTRECRUITMENT_SUCCESS = 'app/RecruitmentWavePage/DELETE_APPLICANTRECRUITMENT_SUCCESS';
export const DELETE_APPLICANTRECRUITMENT_FAILURE = 'app/RecruitmentWavePage/DELETE_APPLICANTRECRUITMENT_FAILURE';

export const CREATE_TESTAPPLICANTRECRUITMENT = 'app/RecruitmentWavePage/CREATE_TESTAPPLICANTRECRUITMENT';
export const CREATE_TESTAPPLICANTRECRUITMENT_SUCCESS = 'app/RecruitmentWavePage/CREATE_TESTAPPLICANTRECRUITMENT_SUCCESS';
export const CREATE_TESTAPPLICANTRECRUITMENT_FAILURE = 'app/RecruitmentWavePage/CREATE_TESTAPPLICANTRECRUITMENT_FAILURE';

export const UPDATE_TESTAPPLICANTRECRUITMENT = 'app/RecruitmentWavePage/UPDATE_TESTAPPLICANTRECRUITMENT';
export const UPDATE_TESTAPPLICANTRECRUITMENT_SUCCESS = 'app/RecruitmentWavePage/UPDATE_TESTAPPLICANTRECRUITMENT_SUCCESS';
export const UPDATE_TESTAPPLICANTRECRUITMENT_FAILURE = 'app/RecruitmentWavePage/UPDATE_TESTAPPLICANTRECRUITMENT_FAILURE';

export const DELETE_TESTAPPLICANTRECRUITMENT = 'app/RecruitmentWavePage/DELETE_TESTAPPLICANTRECRUITMENT';
export const DELETE_TESTAPPLICANTRECRUITMENT_SUCCESS = 'app/RecruitmentWavePage/DELETE_TESTAPPLICANTRECRUITMENT_SUCCESS';
export const DELETE_TESTAPPLICANTRECRUITMENT_FAILURE = 'app/RecruitmentWavePage/DELETE_TESTAPPLICANTRECRUITMENT_FAILURE';

export const GET_HUMAN_RESOURCE = 'app/RecruitmentWavePage/GET_HUMAN_RESOURCE';
export const GET_HUMAN_RESOURCE_SUCCESS = 'app/RecruitmentWavePage/GET_HUMAN_RESOURCE_SUCCESS';
export const GET_HUMAN_RESOURCE_FAILURE = 'app/RecruitmentWavePage/GET_HUMAN_RESOURCE_FAILURE';

export const GET_ROLE_GROUP = 'app/RecruitmentWavePage/GET_ROLE_GROUP';
export const GET_ROLE_GROUP_SUCCESS = 'app/RecruitmentWavePage/GET_ROLE_GROUP_SUCCESS';
export const GET_ROLE_GROUP_FAILURE = 'app/RecruitmentWavePage/GET_ROLE_GROUP_FAILURE';

export const POST_SWITCH_CANDIDATE = 'app/RecruitmentWavePage/POST_SWITCH_CANDIDATE';
export const POST_SWITCH_CANDIDATE_SUCCESS = 'app/RecruitmentWavePage/POST_SWITCH_CANDIDATE_SUCCESS';
export const POST_SWITCH_CANDIDATE_FAILURE = 'app/RecruitmentWavePage/POST_SWITCH_CANDIDATE_FAILURE';

//đăng tuyển

export const CREATE_APPLICANTRECRUITMENT_AGENCY = 'app/RecruitmentWavePage/CREATE_APPLICANTRECRUITMENT_AGENCY';
export const CREATE_APPLICANTRECRUITMENT_AGENCY_SUCCESS = 'app/RecruitmentWavePage/CREATE_APPLICANTRECRUITMENT_AGENCY_SUCCESS';
export const CREATE_APPLICANTRECRUITMENT_AGENCY_FAILURE = 'app/RecruitmentWavePage/CREATE_APPLICANTRECRUITMENT_AGENCY_FAILURE';

export const UPDATE_APPLICANTRECRUITMENT_AGENCY = 'app/RecruitmentWavePage/UPDATE_APPLICANTRECRUITMENT_AGENCY';
export const UPDATE_APPLICANTRECRUITMENT_AGENCY_SUCCESS = 'app/RecruitmentWavePage/UPDATE_APPLICANTRECRUITMENT_AGENCY_SUCCESS';
export const UPDATE_APPLICANTRECRUITMENT_AGENCY_FAILURE = 'app/RecruitmentWavePage/UPDATE_APPLICANTRECRUITMENT_AGENCY_FAILURE';
export const DELETE_APPLICANTRECRUITMENT_AGENCY = 'app/RecruitmentWavePage/DELETE_APPLICANTRECRUITMENT_AGENCY';
export const DELETE_APPLICANTRECRUITMENT_AGENCY_SUCCESS = 'app/RecruitmentWavePage/DELETE_APPLICANTRECRUITMENT_AGENCY_SUCCESS';
export const DELETE_APPLICANTRECRUITMENT_AGENCY_FAILURE = 'app/RecruitmentWavePage/DELETE_APPLICANTRECRUITMENT_AGENCY_FAILURE';