export const CREATE_ACCOUNT_REQUESTED = 'app/BankAccount/CREATE_ACCOUNT_REQUESTED';
export const CREATE_ACCOUNT_REQUESTED_SUCCEEDED = 'app/BankAccount/CREATE_ACCOUNT_REQUESTED_SUCCEEDED';
export const CREATE_ACCOUNT_REQUESTED_FAILED = 'app/BankAccount/CREATE_ACCOUNT_REQUESTED_FAILED';

export const UPDATE_ACCOUNT_REQUESTED = 'app/BankAccount/UPDATE_ACCOUNT_REQUESTED';
export const UPDATE_ACCOUNT_REQUESTED_SUCCEEDED = 'app/BankAccount/UPDATE_ACCOUNT_REQUESTED_SUCCEEDED';
export const UPDATE_ACCOUNT_REQUESTED_FAILED = 'app/BankAccount/UPDATE_ACCOUNT_REQUESTED_FAILED';

export const UPDATE_PASSWORD_REQUESTED = 'app/BankAccount/UPDATE_PASSWORD_REQUESTED';
export const UPDATE_PASSWORD_REQUESTED_SUCCEEDED = 'app/BankAccount/UPDATE_PASSWORD_REQUESTED_SUCCEEDED';
export const UPDATE_PASSWORD_REQUESTED_FAILED = 'app/BankAccount/UPDATE_PASSWORD_REQUESTED_FAILED';

export const DEFAULT_ACCOUNT_REQUESTED = 'app/BankAccount/DEFAULT_ACCOUNT_REQUESTED';

export const MERGE_DATA = 'app/BankAccount/MERGE_DATA';
