/*
 *
 * HocTable constants
 *
 */

export const DEFAULT_ACTION = 'app/HocTable/DEFAULT_ACTION';
export const EDIT_VIEWCONFIG_ACTION = 'app/HocTable/EDIT_VIEWCONFIG_ACTION';
export const EDIT_VIEWCONFIG_SUCCESS = 'app/HocTable/EDIT_VIEWCONFIG_SUCCESS_ACTION';
export const EDIT_VIEWCONFIG_FAIL = 'app/HocTable/EDIT_VIEWCONFIG_FAIL_ACTION';
export const GET_DYNAMIC_FORM_ACTION = 'app/HocTable/GET_DYNAMIC_FORM_ACTION';
export const GET_DYNAMIC_FORM_SUCCESS = 'app/HocTable/GET_DYNAMIC_FORM_SUCCESS_ACTION';
export const GET_DYNAMIC_FORM_FAIL = 'app/HocTable/GET_DYNAMIC_FORM_FAIL_ACTION';
export const EXPORT_FORM_ACTION = 'app/HocTable/EXPORT_FORM_ACTION';

export const CREATE_APPROVE = 'app/HocTable/CREATE_APPROVE';
export const CREATE_APPROVE_SUCCESS = 'app/HocTable/CREATE_APPROVE_SUCCESS';
export const CREATE_APPROVE_FAILED = 'app/HocTable/CREATE_APPROVE_FAILED';

export const SET_APPROVE_FINISH = 'app/HocTable/SET_APPROVE_FINISH';
export const SET_APPROVE_FINISH_SUCCESS = 'app/HocTable/SET_APPROVE_FINISH_SUCCESS';
export const SET_APPROVE_FINISH_ERROR = 'app/HocTable/SET_APPROVE_FINISH_ERROR';
