/*
 *
 * ReportPage constants
 *
 */

export const DEFAULT_ACTION = 'app/ReportPage/DEFAULT_ACTION';

// tổng hợp chi phí bộ phận và khoản mục
export const GET_SUM_IN_YEAR = 'app/ReportPage/GET_SUM_IN_YEAR';
export const GET_SUM_IN_YEAR_SUCCESS = 'app/ReportPage/GET_SUM_IN_YEAR_SUCCESS';
export const GET_SUM_IN_YEAR_FAILURE = 'app/ReportPage/GET_SUM_IN_YEAR_FAILURE';

export const GET_CHARGE_PROPORTION = 'app/ReportPage/GET_CHARGE_PROPORTION';
export const GET_CHARGE_PROPORTION_SUCCESS = 'app/ReportPage/GET_CHARGE_PROPORTION_SUCCESS';
export const GET_CHARGE_PROPORTION_FAILURE = 'app/ReportPage/GET_CHARGE_PROPORTION_FAILURE';

// tổng hợp doanh số theo khách hàng và hàng hóa
export const GET_SUM_REVENUE_COST_IN_YEAR = 'app/ReportPage/GET_SUM_REVENUE_COST_IN_YEAR';
export const GET_SUM_REVENUE_COST_IN_YEAR_SUCCESS = 'app/ReportPage/GET_SUM_REVENUE_COST_IN_YEAR_SUCCESS';
export const GET_SUM_REVENUE_COST_IN_YEAR_FAILURE = 'app/ReportPage/GET_SUM_REVENUE_COST_IN_YEAR_FAILURE';

export const GET_SUM_REVENUE_INVENTORY_IN_YEAR = 'app/ReportPage/GET_SUM_REVENUE_INVENTORY_IN_YEAR';
export const GET_SUM_REVENUE_INVENTORY_IN_YEAR_SUCCESS = 'app/ReportPage/GET_SUM_REVENUE_INVENTORY_IN_YEAR_SUCCESS';
export const GET_SUM_REVENUE_INVENTORY_IN_YEAR_FAILURE = 'app/ReportPage/GET_SUM_REVENUE_INVENTORY_IN_YEAR_FAILURE';

// Tổng hợp doanh số theo nhân viên kinh doanh
export const GET_DETAILED_SALES_BY_STAFF = 'app/ReportPage/GET_DETAILED_SALES_BY_STAFF';
export const GET_DETAILED_SALES_BY_STAFF_SUCCESS = 'app/ReportPage/GET_DETAILED_SALES_BY_STAFF_SUCCESS';
export const GET_DETAILED_SALES_BY_STAFF_FAILURE = 'app/ReportPage/GET_DETAILED_SALES_BY_STAFF_FAILURE';

export const GET_COMPARE_SALES_PERSON_SALES_OF_YEAR = 'app/ReportPage/GET_COMPARE_SALES_PERSON_SALES_OF_YEAR';
export const GET_COMPARE_SALES_PERSON_SALES_OF_YEAR_SUCCESS = 'app/ReportPage/GET_COMPARE_SALES_PERSON_SALES_OF_YEAR_SUCCESS';
export const GET_COMPARE_SALES_PERSON_SALES_OF_YEAR_FAILURE = 'app/ReportPage/GET_COMPARE_SALES_PERSON_SALES_OF_YEAR_FAILURE';

// Tổng hợp tình hình kinh doanh
export const GET_PROPORTION_OF_COST_BY_ITEM = 'app/ReportPage/GET_PROPORTION_OF_COST_BY_ITEM';
export const GET_PROPORTION_OF_COST_BY_ITEM_SUCCESS = 'app/ReportPage/GET_PROPORTION_OF_COST_BY_ITEM_SUCCESS';
export const GET_PROPORTION_OF_COST_BY_ITEM_FAILURE = 'app/ReportPage/GET_PROPORTION_OF_COST_BY_ITEM_FAILURE';

export const GET_PROPORTION_OF_COST_BY_DEPARTMENT = 'app/ReportPage/GET_PROPORTION_OF_COST_BY_DEPARTMENT';
export const GET_PROPORTION_OF_COST_BY_DEPARTMENT_SUCCESS = 'app/ReportPage/GET_PROPORTION_OF_COST_BY_DEPARTMENT_SUCCESS';
export const GET_PROPORTION_OF_COST_BY_DEPARTMENT_FAILURE = 'app/ReportPage/GET_PROPORTION_OF_COST_BY_DEPARTMENT_FAILURE';