export const GET_ALL_DATA_SALARY = 'app/ConfigSalaryPage/GET_ALL_DATA_SALARY';
export const GET_ALL_DATA_SALARY_SUCCESS = 'app/ConfigSalaryPage/GET_ALL_DATA_SALARY_SUCCESS';
export const GET_ALL_DATA_SALARY_FAILER = 'app/ConfigSalaryPage/GET_ALL_DATA_SALARY_FAILER';

export const UPDATE_DATA_SALARY = 'app/ConfigSalaryPage/UPDATE_DATA_SALARY';
export const UPDATE_DATA_SALARY_SUCCESS = 'app/ConfigSalaryPage/UPDATE_DATA_SALARY_SUCCESS';
export const UPDATE_DATA_SALARY_FAILER = 'app/ConfigSalaryPage/UPDATE_DATA_SALARY_FAILER';

export const GET_ALL_SALARY_FORMULA = 'app/ConfigSalaryPage/GET_ALL_SALARY_FORMULA';
export const GET_ALL_SALARY_FORMULA_SUCCESS = 'app/ConfigSalaryPage/GET_ALL_SALARY_FORMULA_SUCCESS';
export const GET_ALL_SALARY_FORMULA_FAILURE = 'app/ConfigSalaryPage/GET_ALL_SALARY_FORMULA_FAILURE';

export const ADD_SALARY_FORMULA = 'app/ConfigSalaryPage/ADD_SALARY_FORMULA';
export const ADD_SALARY_FORMULA_SUCCESS = 'app/ConfigSalaryPage/ADD_SALARY_FORMULA_SUCCESS';
export const ADD_SALARY_FORMULA_FAILURE = 'app/ConfigSalaryPage/ADD_SALARY_FORMULA_FAILURE';

export const UPDATE_SALARY_FORMULA = 'app/ConfigSalaryPage/UPDATE_SALARY_FORMULA';
export const UPDATE_SALARY_FORMULA_SUCCESS = 'app/ConfigSalaryPage/UPDATE_SALARY_FORMULA_SUCCESS';
export const UPDATE_SALARY_FORMULA_FAILURE = 'app/ConfigSalaryPage/UPDATE_SALARY_FORMULA_FAILURE';

export const DELETE_SALARY_FORMULA = 'app/ConfigSalaryPage/DELETE_SALARY_FORMULA';
export const DELETE_SALARY_FORMULA_SUCCESS = 'app/ConfigSalaryPage/DELETE_SALARY_FORMULA_SUCCESS';
export const DELETE_SALARY_FORMULA_FAILURE = 'app/ConfigSalaryPage/DELETE_SALARY_FORMULA_FAILURE';

export const GET_ATTRIBUTE_FORMULA = 'app/ConfigSalaryPage/GET_ATTRIBUTE_FORMULA';
export const GET_ATTRIBUTE_FORMULA_SUCCESS = 'app/ConfigSalaryPage/GET_ATTRIBUTE_FORMULA_SUCCESS';
export const GET_ATTRIBUTE_FORMULA_FAILURE = 'app/ConfigSalaryPage/GET_ATTRIBUTE_FORMULA_FAILURE';

export const ADD_ATTRIBUTE_FORMULA = 'app/ConfigSalaryPage/ADD_ATTRIBUTE_FORMULA';
export const ADD_ATTRIBUTE_FORMULA_SUCCESS = 'app/ConfigSalaryPage/ADD_ATTRIBUTE_FORMULA_SUCCESS';
export const ADD_ATTRIBUTE_FORMULA_FAILURE = 'app/ConfigSalaryPage/ADD_ATTRIBUTE_FORMULA_FAILURE';

export const UPDATE_ATTRIBUTE_FORMULA = 'app/ConfigSalaryPage/UPDATE_ATTRIBUTE_FORMULA';
export const UPDATE_ATTRIBUTE_FORMULA_SUCCESS = 'app/ConfigSalaryPage/UPDATE_ATTRIBUTE_FORMULA_SUCCESS';
export const UPDATE_ATTRIBUTE_FORMULA_FAILURE = 'app/ConfigSalaryPage/UPDATE_ATTRIBUTE_FORMULA_FAILURE';

export const DELETE_ATTRIBUTE_FORMULA = 'app/ConfigSalaryPage/DELETE_ATTRIBUTE_FORMULA';
export const DELETE_ATTRIBUTE_FORMULA_SUCCESS = 'app/ConfigSalaryPage/DELETE_ATTRIBUTE_FORMULA_SUCCESS';
export const DELETE_ATTRIBUTE_FORMULA_FAILURE = 'app/ConfigSalaryPage/DELETE_ATTRIBUTE_FORMULA_FAILURE';

export const GET_LIST_ATTRIBUTE = 'app/ConfigSalaryPage/GET_LIST_ATTRIBUTE';
export const GET_LIST_ATTRIBUTE_SUCCESS = 'app/ConfigSalaryPage/GET_LIST_ATTRIBUTE_SUCCESS';
export const GET_LIST_ATTRIBUTE_FAILURE = 'app/ConfigSalaryPage/GET_LIST_ATTRIBUTE_FAILURE';


// thuong du an
export const GET_PROJECT_BONUS = 'app/ConfigSalaryPage/GET_PROJECT_BONUS';
export const GET_PROJECT_BONUS_SUCCESS = 'app/ConfigSalaryPage/GET_PROJECT_BONUS_SUCCESS';
export const GET_PROJECT_BONUS_FAILURE = 'app/ConfigSalaryPage/GET_PROJECT_BONUS_FAILURE';

export const ADD_PROJECT_BONUS = 'app/ConfigSalaryPage/ADD_PROJECT_BONUS';
export const ADD_PROJECT_BONUS_SUCCESS = 'app/ConfigSalaryPage/ADD_PROJECT_BONUS_SUCCESS';
export const ADD_PROJECT_BONUS_FAILURE = 'app/ConfigSalaryPage/ADD_PROJECT_BONUS_FAILURE';

export const UPDATE_PROJECT_BONUS = 'app/ConfigSalaryPage/UPDATE_PROJECT_BONUS';
export const UPDATE_PROJECT_BONUS_SUCCESS = 'app/ConfigSalaryPage/UPDATE_PROJECT_BONUS_SUCCESS';
export const UPDATE_PROJECT_BONUS_FAILURE = 'app/ConfigSalaryPage/UPDATE_PROJECT_BONUS_FAILURE';

export const DELETE_PROJECT_BONUS = 'app/ConfigSalaryPage/DELETE_PROJECT_BONUS';
export const DELETE_PROJECT_BONUS_SUCCESS = 'app/ConfigSalaryPage/DELETE_PROJECT_BONUS_SUCCESS';
export const DELETE_PROJECT_BONUS_FAILURE = 'app/ConfigSalaryPage/DELETE_PROJECT_BONUS_FAILURE';

// them cong thuc tinh don le
export const ADD_SINGLE_ATTRIBUTE_FORMULA = 'app/ConfigSalaryPage/ADD_SINGLE_ATTRIBUTE_FORMULA';
export const ADD_SINGLE_ATTRIBUTE_FORMULA_SUCCESS = 'app/ConfigSalaryPage/ADD_SINGLE_ATTRIBUTE_FORMULA_SUCCESS';
export const ADD_SINGLE_ATTRIBUTE_FORMULA_FAILURE = 'app/ConfigSalaryPage/ADD_SINGLE_ATTRIBUTE_FORMULA_FAILURE';

export const UPDATE_SINGLE_ATTRIBUTE_FORMULA = 'app/ConfigSalaryPage/UPDATE_SINGLE_ATTRIBUTE_FORMULA';
export const UPDATE_SINGLE_ATTRIBUTE_FORMULA_SUCCESS = 'app/ConfigSalaryPage/UPDATE_SINGLE_ATTRIBUTE_FORMULA_SUCCESS';
export const UPDATE_SINGLE_ATTRIBUTE_FORMULA_FAILURE = 'app/ConfigSalaryPage/UPDATE_SINGLE_ATTRIBUTE_FORMULA_FAILURE';