export const CREATE_ACCOUNT_REQUESTED = 'app/LtAccount/CREATE_ACCOUNT_REQUESTED';
export const CREATE_ACCOUNT_REQUESTED_SUCCEEDED = 'app/LtAccount/CREATE_ACCOUNT_REQUESTED_SUCCEEDED';
export const CREATE_ACCOUNT_REQUESTED_FAILED = 'app/LtAccount/CREATE_ACCOUNT_REQUESTED_FAILED';

export const MERGE_DATA = 'app/LtAccount/MERGE_DATA';
